name: chat_isar_firebase
description: "App de mensajería offline-first con Isar y Firebase Chat."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base de Datos Local (Isar Core)
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.2

  # Firebase Core & Sync (Versiones actualizadas libre de flags -G de gRPC)
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  
  # UI Tools y Utilidades
  device_info_plus: ^10.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3
  photo_manager: ^3.0.0
  permission_handler: ^11.3.1
  workmanager: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: 3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true