// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuvEfFy-Rlkb_biceYv2eZbe59QxkEuY',
    appId: '1:331155115177:web:30a85bb4ae7da5ccf8edb8',
    messagingSenderId: '331155115177',
    projectId: 'rardak-auditoria',
    authDomain: 'rardak-auditoria.firebaseapp.com',
    storageBucket: 'rardak-auditoria.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMeR4sosYsG8gAI1EdSOLhH38ee-pENw',
    appId: '1:331155115177:android:ee41e169df5664b4f8edb8',
    messagingSenderId: '331155115177',
    projectId: 'rardak-auditoria',
    storageBucket: 'rardak-auditoria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbWD4e0lsv3BkChOV0EJyrxtKZdI6aZQ',
    appId: '1:331155115177:ios:1cc91e807e6cec7af8edb8',
    messagingSenderId: '331155115177',
    projectId: 'rardak-auditoria',
    storageBucket: 'rardak-auditoria.firebasestorage.app',
    iosBundleId: 'com.example.chatIsarFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGbWD4e0lsv3BkChOV0EJyrxtKZdI6aZQ',
    appId: '1:331155115177:ios:1cc91e807e6cec7af8edb8',
    messagingSenderId: '331155115177',
    projectId: 'rardak-auditoria',
    storageBucket: 'rardak-auditoria.firebasestorage.app',
    iosBundleId: 'com.example.chatIsarFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjuvEfFy-Rlkb_biceYv2eZbe59QxkEuY',
    appId: '1:331155115177:web:35587225cdc81938f8edb8',
    messagingSenderId: '331155115177',
    projectId: 'rardak-auditoria',
    authDomain: 'rardak-auditoria.firebaseapp.com',
    storageBucket: 'rardak-auditoria.firebasestorage.app',
  );
}
