# Descomentado y configurado en iOS 13.0 como mínimo
platform :ios, '13.0'

# Ignorar advertencias globales de pods
# ignore_all_warnings!

global_platform = '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_plugin_pods File.dirname(File.realpath(__FILE__))
end

# Script Post-Install para forzar a que TODOS los plugins usen iOS 13.0
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end